### ISSUE TITLE
Proposal: Change `quote-props` string option from `as-needed` to `consistent-as-needed`

### ISSUE THREAD

**Issue by junhaoliao** [y-scope/eslint-config-yscope#1]
# Configuration
https://github.com/y-scope/eslint-config-yscope/blob/049afc68f91072736786fdee2de868e581359e44/common.js#L1278

# Docs
https://eslint.style/rules/js/quote-props

**Comment by junhaoliao** [comment]
Opinions welcomed. @kirkrodrigues @Henry8192

**Comment by kirkrodrigues** [comment]
As long as it's automatable, sgtm.

**Comment by junhaoliao** [comment]
Fixed in b3972b3946ebd877519e3fc163b7a38a93cdceb0 .
